name: CI Pipeline

on:
  push:
    branches:
      - devops  # Changez selon votre branche principale
  pull_request:
    branches:
      - devops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Changez selon vos besoins

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt

      - name: Run tests
        run: |
          pytest  # Exécutez vos tests ici

      - name: Deploy (Optional)
        run: |
          echo "Déploiement de l'application..."
          # Ajoutez ici vos commandes de déploiement